config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'
  get  'show', to: 'static_pages#show', as: 'profile'

  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  resources :genres
  resources :books
  resources :transactions, only: [:index, :show, :new, :create]
  resources :reviews #do
   # get "/new(:book_id)(:user_id)", action: :new, on: :collection, as: "new_bid_uid"
   #get "/new(:book_id)(:user_id)", to: 'reviews#new', on: :collection, as: "new_bid_uid"
  #end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :genre, class_name: 'Genre'

  validates :title, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :book, class_name: 'Book'

  validates :review_description, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :book, class_name: 'Book'

  validates :transaction_comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "You have created a Book"
      redirect_to @book
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:success] = "You have updated a Book"
      redirect_to @book
    else
      render 'edit'
    end
  end

  private

    def book_params
      params.require(:book).permit(:title, :description, :author_id, :genre_id)
    end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
    @genre = Genre.new(creator: current_user)
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success] = "You have created a Genre"
      redirect_to @genre
    else
      render 'new'
    end
  end

  private

    def genre_params
      params.require(:genre).permit(:name, :creator_id)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @review = Review.find(review_params[:id])
  end

  def new
    @user_id = params[:user_id]
    @book_id = params[:book_id]
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to @review
    else
      render 'new'
    end
  end

  private

    def review_params
      params.permit(:review_description, :user_id, :book_id)
    end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def show
    @user = User.find(current_user.id)
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  
  def index
    @transactions = Transaction.all
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    if @transaction.save
      flash[:success] = "You have Purchased a Book"
      redirect_to @transaction
    else
      render 'new'
    end
  end

  private

    def transaction_params
      params.permit(:transaction_comment, :user_id, :book_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      bypass_sign_in @user, scope: :user
      redirect_to index_path(current_user)
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.slim
h3
  | Edit Book:
.col-sm-6.col-sm-offset-3
  = form_for(@book) do |f|
    .field
      = f.label :title, "Book Title"
      br
      = f.text_field :title, :autocomplete => "off"
    .field
      = f.label :description, "Book Description"
      br
      = f.text_field :description, :autocomplete => "off"
    .field
      = f.label :genre_id
      br
      = f.collection_select :genre_id, Genre.order(:name), :id, :name, include_blank: false
    = f.hidden_field :author_id, :value => current_user.id
    .action_container
      br
      = f.submit
      

app/views/books/index.html.slim
p
  | List of All Books: 
- @books.each do |book|
  li
    = book.title
    |   
    = book.description
    |   
    = User.find(book.author_id).first_name
    |   
    = User.find(book.author_id).last_name
    |   
    = Genre.find(book.genre_id).name
    |   
    = link_to "Edit", edit_book_path(book.id)
    |  | 
    = link_to "View", book_path(book.id)
    |  | 
    = link_to "Purchase", transactions_path(:transaction_comment => "Default comment",:user_id => current_user.id, :book_id => book.id), :method => :post
    |  | 
    = link_to "Review", new_review_path(:user_id => current_user.id, :book_id => book.id)
br

app/views/books/new.html.slim
h3
  | Add a Book:
.col-sm-6.col-sm-offset-3
  = form_for(@book) do |f|
    .field
      = f.label :title, "Book Title"
      br
      = f.text_field :title, :autocomplete => "off"
    .field
      = f.label :description, "Book Description"
      br
      = f.text_field :description, :autocomplete => "off"
    .field
      = f.label :genre_id
      br
      = f.collection_select :genre_id, Genre.order(:name), :id, :name, include_blank: false
    = f.hidden_field :author_id, :value => current_user.id
    .action_container
      br
      = f.submit
      

app/views/books/show.html.slim
p
  | Current Book: 
li
  | Title: 
  = @book.title
li
  | Description: 
  = @book.description
li
  | Author: 
  = User.find(@book.author_id).first_name
  = User.find(@book.author_id).last_name
li
  | Genre: 
  = Genre.find(@book.genre_id).name
li
  = link_to "Purchase", transactions_path(:transaction_comment => "Purchase from Book Show Page",:user_id => current_user.id, :book_id => @book.id), :method => :post
li
  = link_to "All Genre's", genres_path
br

app/views/genres/index.html.slim
p
  | All Current Genres: 
- @genres.each do |genre|
  li
    = genre.name
br
= link_to "Continue", books_path
br

app/views/genres/new.html.slim
h3
  | Add a Genre
  = form_for(@genre) do |f|
    .field
      = f.label :name, "Genre Name"
      br
      = f.text_field :name, :autocomplete => "off"
    = f.hidden_field :creator_id
    .action_container
      = f.submit

app/views/genres/show.html.slim
h2
  | Genre Name: 
  = @genre.name
| Genre Creator: 
= User.find(@genre.creator_id).first_name
|   
= User.find(@genre.creator_id).last_name
br
= link_to "Continue", genres_path
br

app/views/reviews/new.html.slim
h3
  | Add a Review for: 
  br
  = form_for(@review) do |f|
    .field
      = f.label :review_description, "Review Comment:"
      br
      = f.text_field :review_description, :autocomplete => "off"
    = f.hidden_field :user_id, :value => @user_id
    = f.hidden_field :book_id, :value => @book_id
    .action_container
      = f.submit

app/views/static_pages/index.html.slim
h1 Welcome to The BookStore
br/

app/views/static_pages/show.html.slim
h1 Welcome to The BookStore

p
  | Name: 
  = @user.first_name
  br
  | Surname: 
  = @user.last_name
  br
  | Email: 
  = @user.email
  br

app/views/transactions/index.html.slim
.container
  .row
    p
      | List of All Purchases: 
    - @transactions.each do |transaction|
      | Comments: 
      = transaction.transaction_comment
      li
        | Buyer: 
        = User.find(transaction.user_id).first_name
        '
        = User.find(transaction.user_id).last_name
      li
        | Book Title: 
        = Book.find(transaction.book_id).title
      li
        | Book Author: 
        = User.find(Book.find(transaction.book_id).author_id).first_name
        '
        = User.find(Book.find(transaction.book_id).author_id).last_name
    br

app/views/transactions/new.html.slim
#sign-up-form.container
  .row
    h3
      | Buy this Book:
    .col-sm-6.col-sm-offset-3
      = form_for(@transaction) do |f|
        .field
          = f.label :transaction_comment, "Add a comment:"
          br
          = f.text_field :transaction_comment, :autocomplete => "off"
        .field
          = f.label :book_id
          br
          = f.collection_select :book_id, Book.order(:title), :id, :title, include_blank: false
        = f.hidden_field :user_id, :value => current_user.id
        .action_container
          br
          = f.submit
          

app/views/transactions/show.html.slim
.container
  .row
    p
      | Current Transaction: 
    li
      | Comments: 
      = @transaction.transaction_comment
    li
      | Buyer: 
      = User.find(@transaction.user_id).first_name
      '
      = User.find(@transaction.user_id).last_name
    li
      | Book Title: 
      = Book.find(@transaction.book_id).title
    li
      | Book Author: 
      = User.find(Book.find(@transaction.book_id).author_id).first_name
      '
      = User.find(Book.find(@transaction.book_id).author_id).last_name
    br
    = link_to 'Continue', transactions_path
    br

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>